trigger:
  - master
pr:
  - master

pool:
  vmImage: 'macos-latest'

steps:
  - task: Xcode@5
    inputs:
      actions: 'build'
      configuration: 'Debug'
      sdk: 'iphoneos'
      xcWorkspacePath: 'ios/KaMPStarteriOS.xcworkspace'
      scheme: 'KaMPStarteriOS'
      packageApp: false
      publishJUnitResults: true