version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    labels: ["dependencies"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]