/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param uuid 
 * @param displayName 
 * @param sex 
 * @param warnings 
 */
@Serializable
data class Client (
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    @SerialName(value = "display_name") val displayName: kotlin.String? = null,
    @SerialName(value = "sex") val sex: Client.Sex? = null,
    @SerialName(value = "warnings") val warnings: kotlin.collections.List<Client.Warnings>? = null
) {

    /**
     * 
     * Values: MALE,FEMALE
     */
    @Serializable
    enum class Sex(val value: kotlin.String) {
        @SerialName(value = "male") MALE("male"),
        @SerialName(value = "female") FEMALE("female");
    }
    /**
     * 
     * Values: HEALTH_EVALUATION_NOT_CONSENTED
     */
    @Serializable
    enum class Warnings(val value: kotlin.String) {
        @SerialName(value = "health_evaluation_not_consented") HEALTH_EVALUATION_NOT_CONSENTED("health_evaluation_not_consented");
    }
}

