/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.ClientWorkoutCalculatedEstimates

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param uuid 
 * @param type 
 * @param activityType 
 * @param completedAt iso8601 formatted time of when the exercise was completed
 * @param title 
 * @param duration seconds
 * @param calculatedEstimates 
 */
@Serializable
data class ClientWorkout (
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    @SerialName(value = "type") val type: ClientWorkout.Type? = null,
    @SerialName(value = "activity_type") val activityType: ClientWorkout.ActivityType? = null,
    /* iso8601 formatted time of when the exercise was completed */
    @SerialName(value = "completed_at") val completedAt: kotlin.String? = null,
    @SerialName(value = "title") val title: kotlin.String? = null,
    /* seconds */
    @SerialName(value = "duration") val duration: kotlin.Int? = null,
    @SerialName(value = "calculated_estimates") val calculatedEstimates: ClientWorkoutCalculatedEstimates? = null
) {

    /**
     * 
     * Values: OUTDOOR,TREADMILL,WATT_MACHINE,GENERIC,STRENGTH
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "outdoor") OUTDOOR("outdoor"),
        @SerialName(value = "treadmill") TREADMILL("treadmill"),
        @SerialName(value = "watt_machine") WATT_MACHINE("watt_machine"),
        @SerialName(value = "generic") GENERIC("generic"),
        @SerialName(value = "strength") STRENGTH("strength");
    }
    /**
     * 
     * Values: WALKING,RUNNING,CYCLING,CROSS_COUNTRY_SKIING,SWIMMING,ROWING,OTHER
     */
    @Serializable
    enum class ActivityType(val value: kotlin.String) {
        @SerialName(value = "walking") WALKING("walking"),
        @SerialName(value = "running") RUNNING("running"),
        @SerialName(value = "cycling") CYCLING("cycling"),
        @SerialName(value = "cross_country_skiing") CROSS_COUNTRY_SKIING("cross_country_skiing"),
        @SerialName(value = "swimming") SWIMMING("swimming"),
        @SerialName(value = "rowing") ROWING("rowing"),
        @SerialName(value = "other") OTHER("other");
    }
}

