/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param teamId 
 * @param teamUuid 
 * @param teamName 
 * @param currentRank 
 * @param pastRanks The ranks awarded in previous weeks of the contest
 * @param score The team average score or average rank if contest is finished
 */
@Serializable
data class ContestsLeaderboardRanking (
    @SerialName(value = "team_id") val teamId: kotlin.Int? = null,
    @SerialName(value = "team_uuid") val teamUuid: kotlin.String? = null,
    @SerialName(value = "team_name") val teamName: kotlin.String? = null,
    @SerialName(value = "current_rank") val currentRank: kotlin.Int? = null,
    /* The ranks awarded in previous weeks of the contest */
    @SerialName(value = "past_ranks") val pastRanks: kotlin.collections.List<kotlin.Int>? = null,
    /* The team average score or average rank if contest is finished */
    @SerialName(value = "score") val score: kotlin.Int? = null
)

