/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.WorkoutExerciseInput
import com.myworkout.kotlin.api.models.WorkoutStageInput

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param type 
 * @param source Identifies how the workout has been registered. Manual is based purely on user input, while recorded means it has been captured by the client.
 * @param startedAt 
 * @param duration seconds
 * @param id UUID for exercise, API will automatically generate one if empty.
 * @param activityType 
 * @param recordingDevice An identifier to be able to identify which device/model was used to record a given workout.
 * @param transmission 
 * @param displayHealthEvaluation Does the user want to display health evaluation for this workout
 * @param title 
 * @param bodyWeight Weight in kg, precision 5.2
 * @param stages 
 * @param exercises 
 */
@Serializable
data class CreateWorkoutInput (
    @SerialName(value = "type") @Required val type: CreateWorkoutInput.Type,
    /* Identifies how the workout has been registered. Manual is based purely on user input, while recorded means it has been captured by the client. */
    @SerialName(value = "source") @Required val source: CreateWorkoutInput.Source,
    @SerialName(value = "started_at") @Required val startedAt: kotlin.String,
    /* seconds */
    @SerialName(value = "duration") @Required val duration: kotlin.Int,
    /* UUID for exercise, API will automatically generate one if empty. */
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "activity_type") val activityType: CreateWorkoutInput.ActivityType? = null,
    /* An identifier to be able to identify which device/model was used to record a given workout. */
    @SerialName(value = "recording_device") val recordingDevice: kotlin.String? = null,
    @SerialName(value = "transmission") val transmission: CreateWorkoutInput.Transmission? = null,
    /* Does the user want to display health evaluation for this workout */
    @SerialName(value = "display_health_evaluation") val displayHealthEvaluation: kotlin.Boolean? = null,
    @SerialName(value = "title") val title: kotlin.String? = null,
    /* Weight in kg, precision 5.2 */
    @SerialName(value = "body_weight") val bodyWeight: kotlin.Double? = null,
    @SerialName(value = "stages") val stages: kotlin.collections.List<WorkoutStageInput>? = null,
    @SerialName(value = "exercises") val exercises: kotlin.collections.List<WorkoutExerciseInput>? = null
) {

    /**
     * 
     * Values: OUTDOOR,TREADMILL,WATT_MACHINE,GENERIC,STRENGTH
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "outdoor") OUTDOOR("outdoor"),
        @SerialName(value = "treadmill") TREADMILL("treadmill"),
        @SerialName(value = "watt_machine") WATT_MACHINE("watt_machine"),
        @SerialName(value = "generic") GENERIC("generic"),
        @SerialName(value = "strength") STRENGTH("strength");
    }
    /**
     * Identifies how the workout has been registered. Manual is based purely on user input, while recorded means it has been captured by the client.
     * Values: RECORDED,MANUAL
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "recorded") RECORDED("recorded"),
        @SerialName(value = "manual") MANUAL("manual");
    }
    /**
     * 
     * Values: WALKING,RUNNING,CYCLING,CROSS_COUNTRY_SKIING,SWIMMING,ROWING,OTHER
     */
    @Serializable
    enum class ActivityType(val value: kotlin.String) {
        @SerialName(value = "walking") WALKING("walking"),
        @SerialName(value = "running") RUNNING("running"),
        @SerialName(value = "cycling") CYCLING("cycling"),
        @SerialName(value = "cross_country_skiing") CROSS_COUNTRY_SKIING("cross_country_skiing"),
        @SerialName(value = "swimming") SWIMMING("swimming"),
        @SerialName(value = "rowing") ROWING("rowing"),
        @SerialName(value = "other") OTHER("other");
    }
    /**
     * 
     * Values: IN_PROGRESS,DONE
     */
    @Serializable
    enum class Transmission(val value: kotlin.String) {
        @SerialName(value = "in_progress") IN_PROGRESS("in_progress"),
        @SerialName(value = "done") DONE("done");
    }
}

