/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*

/**
* 
* Values: WORKOUT_DATA,HEALTH_EVALUATION_DATA,PROFILE_DATA
*/
@Serializable
enum class DataPermission(val value: kotlin.String) {


    @SerialName(value = "workout_data")
    WORKOUT_DATA("workout_data"),

    @SerialName(value = "health_evaluation_data")
    HEALTH_EVALUATION_DATA("health_evaluation_data"),

    @SerialName(value = "profile_data")
    PROFILE_DATA("profile_data");


    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }
}

