/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Which properties are sent depends on the \"type\" of the FeedActivity. Following is a mapping of which properties are sent with each type: event_workout_points: [points], event_gained_handicap_points: [points], event_contest_has_started: [contest_uuid, contest_name, start_at, finish_at], event_contest_has_ended: [contest_uuid, contest_name, position], event_contest_weekly_bout_ended: [contest_uuid, contest_name, position, score, current_contest_week, weeks_remaining], event_team_member_added: [], event_team_member_removed: [], message: [message]
 * @param message 
 * @param points 
 * @param contestUuid 
 * @param contestName 
 * @param position 
 * @param score 
 * @param currentContestWeek 
 * @param weeksRemaining 
 * @param startAt iso8601 formatted time of when the contest starts
 * @param finishAt iso8601 formatted time of when the contest finishes
 */
@Serializable
data class FeedActivityActivityData (
    @SerialName(value = "message") val message: kotlin.String? = null,
    @SerialName(value = "points") val points: kotlin.Int? = null,
    @SerialName(value = "contest_uuid") val contestUuid: kotlin.String? = null,
    @SerialName(value = "contest_name") val contestName: kotlin.String? = null,
    @SerialName(value = "position") val position: kotlin.Double? = null,
    @SerialName(value = "score") val score: kotlin.Double? = null,
    @SerialName(value = "current_contest_week") val currentContestWeek: kotlin.Double? = null,
    @SerialName(value = "weeks_remaining") val weeksRemaining: kotlin.Double? = null,
    /* iso8601 formatted time of when the contest starts */
    @SerialName(value = "start_at") val startAt: kotlin.String? = null,
    /* iso8601 formatted time of when the contest finishes */
    @SerialName(value = "finish_at") val finishAt: kotlin.String? = null
)

