/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param first URL to the first page in results
 * @param last URL to the last page in results
 * @param prev URL to the previous page in results or empty if there is no previous page
 * @param next URL to the next page in results or empty if there is no next page
 */
@Serializable
data class GetClientWorkoutsResponseLinks (
    /* URL to the first page in results */
    @SerialName(value = "first") val first: kotlin.String? = null,
    /* URL to the last page in results */
    @SerialName(value = "last") val last: kotlin.String? = null,
    /* URL to the previous page in results or empty if there is no previous page */
    @SerialName(value = "prev") val prev: kotlin.String? = null,
    /* URL to the next page in results or empty if there is no next page */
    @SerialName(value = "next") val next: kotlin.String? = null
)

