/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param startAt ISO8601
 * @param endAt ISO8601
 * @param duration seconds
 */
@Serializable
data class HitPeriod (
    /* ISO8601 */
    @SerialName(value = "start_at") @Required val startAt: kotlin.String,
    /* ISO8601 */
    @SerialName(value = "end_at") @Required val endAt: kotlin.String,
    /* seconds */
    @SerialName(value = "duration") @Required val duration: kotlin.Int
)

