/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param accessToken 
 * @param issuedTokenType 
 * @param tokenType 
 * @param expiresIn How many seconds until the (access? refresh?)-token expires
 * @param scope 
 * @param refreshToken 
 */
@Serializable
data class LoginUsingIdentityProviderResponse (
    @SerialName(value = "access_token") @Required val accessToken: kotlin.String,
    @SerialName(value = "issued_token_type") @Required val issuedTokenType: kotlin.String,
    @SerialName(value = "token_type") @Required val tokenType: kotlin.String,
    /* How many seconds until the (access? refresh?)-token expires */
    @SerialName(value = "expires_in") val expiresIn: kotlin.Int? = null,
    @SerialName(value = "scope") val scope: kotlin.String? = null,
    @SerialName(value = "refresh_token") val refreshToken: kotlin.String? = null
)

