/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param uuid 
 * @param name Name of organization
 * @param contactPerson 
 * @param contactEmail 
 * @param contactPhone 
 * @param isPremium 
 * @param language 
 */
@Serializable
data class ManagedOrganization (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    /* Name of organization */
    @SerialName(value = "name") val name: kotlin.String? = null,
    @SerialName(value = "contact_person") val contactPerson: kotlin.String? = null,
    @SerialName(value = "contact_email") val contactEmail: kotlin.String? = null,
    @SerialName(value = "contact_phone") val contactPhone: kotlin.String? = null,
    @SerialName(value = "is_premium") val isPremium: kotlin.Boolean? = null,
    @SerialName(value = "language") val language: kotlin.String? = null
)

