/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param title 
 * @param body 
 * @param link 
 * @param type 
 * @param readAt iso8601 formatted time of when the notification was read
 * @param createdAt iso8601 formatted time of when the notification was created
 * @param updatedAt iso8601 formatted time of when the notification was updated
 */
@Serializable
data class Notification (
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "title") val title: kotlin.String? = null,
    @SerialName(value = "body") val body: kotlin.String? = null,
    @SerialName(value = "link") val link: kotlin.String? = null,
    @SerialName(value = "type") val type: kotlin.String? = null,
    /* iso8601 formatted time of when the notification was read */
    @SerialName(value = "read_at") val readAt: kotlin.String? = null,
    /* iso8601 formatted time of when the notification was created */
    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,
    /* iso8601 formatted time of when the notification was updated */
    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null
)

