/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.OrganizationActivationTokenOrganizationDepartments
import com.myworkout.kotlin.api.models.OrganizationActivationTokenOrganizationLinks

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The organization this token will connect the user to
 * @param id 
 * @param uuid 
 * @param name 
 * @param brandName 
 * @param type 
 * @param departments 
 * @param links 
 */
@Serializable
data class OrganizationActivationTokenOrganization (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    @SerialName(value = "name") val name: kotlin.String? = null,
    @SerialName(value = "brand_name") val brandName: kotlin.String? = null,
    @SerialName(value = "type") val type: OrganizationActivationTokenOrganization.Type? = null,
    @SerialName(value = "departments") val departments: kotlin.collections.List<OrganizationActivationTokenOrganizationDepartments>? = null,
    @SerialName(value = "links") val links: OrganizationActivationTokenOrganizationLinks? = null
) {

    /**
     * 
     * Values: COMPANY,INSURANCE,SPORTS_CLUB,GYM,CLINIC
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "company") COMPANY("company"),
        @SerialName(value = "insurance") INSURANCE("insurance"),
        @SerialName(value = "sports_club") SPORTS_CLUB("sports_club"),
        @SerialName(value = "gym") GYM("gym"),
        @SerialName(value = "clinic") CLINIC("clinic");
    }
}

