/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param name Name of the invited user
 * @param email E-mail of the invited user
 * @param phone e.164 compliant phone number of the invited user
 * @param isAdmin 
 * @param token 
 * @param lastSentAt ISO8601 time of when the invitation last was sent
 * @param createdAt ISO8601 time of when the invitation was created
 */
@Serializable
data class OrganizationInviteResponse (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    /* Name of the invited user */
    @SerialName(value = "name") val name: kotlin.String? = null,
    /* E-mail of the invited user */
    @SerialName(value = "email") val email: kotlin.String? = null,
    /* e.164 compliant phone number of the invited user */
    @SerialName(value = "phone") val phone: kotlin.String? = null,
    @SerialName(value = "is_admin") val isAdmin: kotlin.Boolean? = null,
    @SerialName(value = "token") val token: kotlin.String? = null,
    /* ISO8601 time of when the invitation last was sent */
    @SerialName(value = "last_sent_at") val lastSentAt: kotlin.String? = null,
    /* ISO8601 time of when the invitation was created */
    @SerialName(value = "created_at") val createdAt: kotlin.String? = null
)

