/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.DataPermission
import com.myworkout.kotlin.api.models.OrganizationActivationTokenDepartment
import com.myworkout.kotlin.api.models.OrganizationActivationTokenMedia
import com.myworkout.kotlin.api.models.OrganizationActivationTokenOrganization
import com.myworkout.kotlin.api.models.OrganizationMemberRole

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param confirmLink Deprecated, use activation_url in stead
 * @param activationUrl Link to accept the invitation
 * @param uuid 
 * @param name 
 * @param media 
 * @param token 
 * @param invitationName 
 * @param invitationEmail 
 * @param isPremium 
 * @param isUsed 
 * @param type 
 * @param requiredPermissions 
 * @param onboardingText 
 * @param role 
 * @param department 
 * @param organization 
 */
@Serializable
data class OrganizationActivationToken (
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "id") val id: kotlin.Int? = null,
    /* Deprecated, use activation_url in stead */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "confirm_link") val confirmLink: kotlin.String? = null,
    /* Link to accept the invitation */
    @SerialName(value = "activation_url") val activationUrl: kotlin.String? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "name") val name: kotlin.String? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "media") val media: OrganizationActivationTokenMedia? = null,
    @SerialName(value = "token") val token: kotlin.String? = null,
    @SerialName(value = "invitation_name") val invitationName: kotlin.String? = null,
    @SerialName(value = "invitation_email") val invitationEmail: kotlin.String? = null,
    @SerialName(value = "is_premium") val isPremium: kotlin.Boolean? = null,
    @SerialName(value = "is_used") val isUsed: kotlin.Boolean? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "type") val type: OrganizationActivationToken.Type? = null,
    @SerialName(value = "required_permissions") val requiredPermissions: kotlin.collections.List<DataPermission>? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "onboarding_text") val onboardingText: kotlin.String? = null,
    @SerialName(value = "role") val role: OrganizationMemberRole? = null,
    @SerialName(value = "department") val department: OrganizationActivationTokenDepartment? = null,
    @SerialName(value = "organization") val organization: OrganizationActivationTokenOrganization? = null
) {

    /**
     * 
     * Values: COMPANY,INSURANCE,SPORTS_CLUB,GYM,CLINIC
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "company") COMPANY("company"),
        @SerialName(value = "insurance") INSURANCE("insurance"),
        @SerialName(value = "sports_club") SPORTS_CLUB("sports_club"),
        @SerialName(value = "gym") GYM("gym"),
        @SerialName(value = "clinic") CLINIC("clinic");
    }
}

