/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param feature identificator of the feature requiring user's consent
 * @param consentGranted 
 * @param updatedAt Date of when the user updated the state . null if user has not given consent yet.
 */
@Serializable
data class PrivacyConsentState (
    /* identificator of the feature requiring user's consent */
    @SerialName(value = "feature") val feature: PrivacyConsentState.Feature? = null,
    @SerialName(value = "consent_granted") val consentGranted: kotlin.Boolean? = null,
    /* Date of when the user updated the state . null if user has not given consent yet. */
    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null
) {

    /**
     * identificator of the feature requiring user's consent
     * Values: HEALTH_EVALUATION,SHARE_WORKOUTS_IN_TEAM_FEED
     */
    @Serializable
    enum class Feature(val value: kotlin.String) {
        @SerialName(value = "health_evaluation") HEALTH_EVALUATION("health_evaluation"),
        @SerialName(value = "share_workouts_in_team_feed") SHARE_WORKOUTS_IN_TEAM_FEED("share_workouts_in_team_feed");
    }
}

