/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param name team member name
 * @param role 
 * @param status 
 */
@Serializable
data class TeamMembers (
    /* team member name */
    @SerialName(value = "name") val name: kotlin.String? = null,
    @SerialName(value = "role") val role: kotlin.String? = null,
    @SerialName(value = "status") val status: TeamMembers.Status? = null
) {

    /**
     * 
     * Values: ACTIVE,INVITED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "invited") INVITED("invited");
    }
}

