/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param deleteProperties For clients that can't send `null` values on optional properties. They can instead indicate fields to be dropped by adding them here
 */
@Serializable
data class UpdateUserInputMeta (
    /* For clients that can't send `null` values on optional properties. They can instead indicate fields to be dropped by adding them here */
    @SerialName(value = "delete_properties") val deleteProperties: kotlin.collections.List<UpdateUserInputMeta.DeleteProperties>? = null
) {

    /**
     * For clients that can't send `null` values on optional properties. They can instead indicate fields to be dropped by adding them here
     * Values: MAX_HEARTRATE,FIRST_NAME,LAST_NAME
     */
    @Serializable
    enum class DeleteProperties(val value: kotlin.String) {
        @SerialName(value = "max_heartrate") MAX_HEARTRATE("max_heartrate"),
        @SerialName(value = "first_name") FIRST_NAME("first_name"),
        @SerialName(value = "last_name") LAST_NAME("last_name");
    }
}

