/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.UpdateUserInputMeta

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param meta 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param sex 
 * @param birthDate 
 * @param maxHeartrate Max heart rate (BPM)
 * @param language 
 */
@Serializable
data class UpdateUserInput (
    @SerialName(value = "meta") val meta: UpdateUserInputMeta? = null,
    @SerialName(value = "first_name") val firstName: kotlin.String? = null,
    @SerialName(value = "last_name") val lastName: kotlin.String? = null,
    @SerialName(value = "email") val email: kotlin.String? = null,
    @SerialName(value = "sex") val sex: UpdateUserInput.Sex? = null,
    @SerialName(value = "birth_date") val birthDate: kotlin.String? = null,
    /* Max heart rate (BPM) */
    @SerialName(value = "max_heartrate") val maxHeartrate: kotlin.Int? = null,
    @SerialName(value = "language") val language: kotlin.String? = null
) {

    /**
     * 
     * Values: MALE,FEMALE
     */
    @Serializable
    enum class Sex(val value: kotlin.String) {
        @SerialName(value = "male") MALE("male"),
        @SerialName(value = "female") FEMALE("female");
    }
}

