/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.WorkoutExerciseInput
import com.myworkout.kotlin.api.models.WorkoutStageInput

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param type 
 * @param startedAt 
 * @param duration seconds
 * @param activityType 
 * @param displayHealthEvaluation Does the user want to display health evaluation for this workout
 * @param title 
 * @param bodyWeight Weight in kg, precision 5.2
 * @param stages Replace
 * @param exercises 
 */
@Serializable
data class UpdateWorkoutInput (
    @SerialName(value = "type") @Required val type: UpdateWorkoutInput.Type,
    @SerialName(value = "started_at") @Required val startedAt: kotlin.String,
    /* seconds */
    @SerialName(value = "duration") @Required val duration: kotlin.Int,
    @SerialName(value = "activity_type") val activityType: UpdateWorkoutInput.ActivityType? = null,
    /* Does the user want to display health evaluation for this workout */
    @SerialName(value = "display_health_evaluation") val displayHealthEvaluation: kotlin.Boolean? = null,
    @SerialName(value = "title") val title: kotlin.String? = null,
    /* Weight in kg, precision 5.2 */
    @SerialName(value = "body_weight") val bodyWeight: kotlin.Double? = null,
    /* Replace */
    @SerialName(value = "stages") val stages: kotlin.collections.List<WorkoutStageInput>? = null,
    @SerialName(value = "exercises") val exercises: kotlin.collections.List<WorkoutExerciseInput>? = null
) {

    /**
     * 
     * Values: OUTDOOR,TREADMILL,WATT_MACHINE,GENERIC,STRENGTH
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "outdoor") OUTDOOR("outdoor"),
        @SerialName(value = "treadmill") TREADMILL("treadmill"),
        @SerialName(value = "watt_machine") WATT_MACHINE("watt_machine"),
        @SerialName(value = "generic") GENERIC("generic"),
        @SerialName(value = "strength") STRENGTH("strength");
    }
    /**
     * 
     * Values: WALKING,RUNNING,CYCLING,CROSS_COUNTRY_SKIING,SWIMMING,ROWING,OTHER
     */
    @Serializable
    enum class ActivityType(val value: kotlin.String) {
        @SerialName(value = "walking") WALKING("walking"),
        @SerialName(value = "running") RUNNING("running"),
        @SerialName(value = "cycling") CYCLING("cycling"),
        @SerialName(value = "cross_country_skiing") CROSS_COUNTRY_SKIING("cross_country_skiing"),
        @SerialName(value = "swimming") SWIMMING("swimming"),
        @SerialName(value = "rowing") ROWING("rowing"),
        @SerialName(value = "other") OTHER("other");
    }
}

