/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.UserActivityProgressActivities

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param weekHitMinutesProgress The number of HIT minutes the user has accumulated in the current week.
 * @param weekHitMinutesGoal The number of HIT minutes the user aims to accumulate in the current week.
 * @param activities 
 * @param weekGoal 
 * @param weekProgress 
 * @param dayProgress 
 * @param weekStars 
 */
@Serializable
data class UserActivityProgress (
    /* The number of HIT minutes the user has accumulated in the current week. */
    @SerialName(value = "week_hit_minutes_progress") val weekHitMinutesProgress: kotlin.Double? = null,
    /* The number of HIT minutes the user aims to accumulate in the current week. */
    @SerialName(value = "week_hit_minutes_goal") val weekHitMinutesGoal: kotlin.Double? = null,
    @SerialName(value = "activities") val activities: UserActivityProgressActivities? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "week_goal") val weekGoal: kotlin.Double? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "week_progress") val weekProgress: kotlin.Double? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "day_progress") val dayProgress: kotlin.Double? = null,
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "week_stars") val weekStars: kotlin.collections.List<kotlin.String>? = null
)

