/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.Organization
import com.myworkout.kotlin.api.models.UserBusinessClient
import com.myworkout.kotlin.api.models.UserManagedOrganizations
import com.myworkout.kotlin.api.models.UserSubscription

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param uuid 
 * @param businessClient 
 * @param managedOrganizations list of organizations the user can manage
 * @param organizations 
 * @param isPremium 
 * @param displayName 
 * @param userLogin 
 * @param userEmail 
 * @param firstName 
 * @param lastName 
 * @param sex 
 * @param birthDate 
 * @param grants 
 * @param language 
 * @param maxHeartrate Max heart rate (BPM)
 * @param hadPremiumTrial indicate that user has used trial in the past
 * @param latestSubscription 
 * @param organizationsPendingGrants List of organizations for which the user has not accepted or rejected the required permissions
 */
@Serializable
data class User (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    @SerialName(value = "business_client") val businessClient: UserBusinessClient? = null,
    /* list of organizations the user can manage */
    @SerialName(value = "managed_organizations") val managedOrganizations: kotlin.collections.List<UserManagedOrganizations>? = null,
    @SerialName(value = "organizations") val organizations: kotlin.collections.List<Organization>? = null,
    @SerialName(value = "is_premium") val isPremium: kotlin.Boolean? = null,
    @SerialName(value = "display_name") val displayName: kotlin.String? = null,
    @SerialName(value = "user_login") val userLogin: kotlin.String? = null,
    @SerialName(value = "user_email") val userEmail: kotlin.String? = null,
    @SerialName(value = "first_name") val firstName: kotlin.String? = null,
    @SerialName(value = "last_name") val lastName: kotlin.String? = null,
    @SerialName(value = "sex") val sex: User.Sex? = null,
    @SerialName(value = "birth_date") val birthDate: kotlin.String? = null,
    @SerialName(value = "grants") val grants: kotlin.collections.List<User.Grants>? = null,
    @SerialName(value = "language") val language: kotlin.String? = null,
    /* Max heart rate (BPM) */
    @SerialName(value = "max_heartrate") val maxHeartrate: kotlin.Int? = null,
    /* indicate that user has used trial in the past */
    @SerialName(value = "had_premium_trial") val hadPremiumTrial: kotlin.Boolean? = null,
    @SerialName(value = "latest_subscription") val latestSubscription: UserSubscription? = null,
    /* List of organizations for which the user has not accepted or rejected the required permissions */
    @SerialName(value = "organizations_pending_grants") val organizationsPendingGrants: kotlin.collections.List<kotlin.Int>? = null
) {

    /**
     * 
     * Values: MALE,FEMALE
     */
    @Serializable
    enum class Sex(val value: kotlin.String) {
        @SerialName(value = "male") MALE("male"),
        @SerialName(value = "female") FEMALE("female");
    }
    /**
     * 
     * Values: HEALTH_EVALUATION,SHARE_WORKOUTS_IN_TEAM_FEED
     */
    @Serializable
    enum class Grants(val value: kotlin.String) {
        @SerialName(value = "health_evaluation") HEALTH_EVALUATION("health_evaluation"),
        @SerialName(value = "share_workouts_in_team_feed") SHARE_WORKOUTS_IN_TEAM_FEED("share_workouts_in_team_feed");
    }
}

