/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param uuid 
 * @param userId 
 * @param userUuid 
 * @param platform 
 * @param type 
 * @param state The current state of the subscription.
 * @param identifier product key
 * @param expireAt iso8601
 */
@Serializable
data class UserSubscription (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    @SerialName(value = "uuid") val uuid: kotlin.String? = null,
    @SerialName(value = "user_id") val userId: kotlin.Int? = null,
    @SerialName(value = "user_uuid") val userUuid: kotlin.String? = null,
    @SerialName(value = "platform") val platform: UserSubscription.Platform? = null,
    @SerialName(value = "type") val type: UserSubscription.Type? = null,
    /* The current state of the subscription. */
    @SerialName(value = "state") val state: UserSubscription.State? = null,
    /* product key */
    @SerialName(value = "identifier") val identifier: kotlin.String? = null,
    /* iso8601 */
    @SerialName(value = "expire_at") val expireAt: kotlin.String? = null
) {

    /**
     * 
     * Values: IOS,ANDROID
     */
    @Serializable
    enum class Platform(val value: kotlin.String) {
        @SerialName(value = "ios") IOS("ios"),
        @SerialName(value = "android") ANDROID("android");
    }
    /**
     * 
     * Values: TRIAL,PERIODICAL
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "trial") TRIAL("trial"),
        @SerialName(value = "periodical") PERIODICAL("periodical");
    }
    /**
     * The current state of the subscription.
     * Values: ACTIVE,ON_HOLD,CANCELED,EXPIRED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "on_hold") ON_HOLD("on_hold"),
        @SerialName(value = "canceled") CANCELED("canceled"),
        @SerialName(value = "expired") EXPIRED("expired");
    }
}

