/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param previous URL to previous page for paginated results. Empty if currently on last page.
 * @param next URL to next page for paginated results. Empty if currently on last page.
 * @param limit The limit which was applied
 * @param totalCount The total number of videos matching the queried videos
 */
@Serializable
data class VideoCollectionResponsePaging (
    /* URL to previous page for paginated results. Empty if currently on last page. */
    @SerialName(value = "previous") val previous: kotlin.String? = null,
    /* URL to next page for paginated results. Empty if currently on last page. */
    @SerialName(value = "next") val next: kotlin.String? = null,
    /* The limit which was applied */
    @SerialName(value = "limit") val limit: kotlin.Int? = null,
    /* The total number of videos matching the queried videos */
    @SerialName(value = "total_count") val totalCount: kotlin.Int? = null
)

