/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.TrainerResponse
import com.myworkout.kotlin.api.models.VideoCategoryResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param id 
 * @param type 
 * @param title 
 * @param createdAt ISO8601
 * @param updatedAt ISO8601
 * @param description Description of the workout in the workouts language
 * @param lang Language the video content/info is available in
 * @param vimeoCode 
 * @param duration Duration in What format?
 * @param thumbnail What is this? URL? Should probably not be in DB but handled differently
 * @param categories 
 * @param trainers 
 */
@Serializable
data class VideoResponse (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    @SerialName(value = "type") val type: VideoResponse.Type? = null,
    @SerialName(value = "title") val title: kotlin.String? = null,
    /* ISO8601 */
    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,
    /* ISO8601 */
    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,
    /* Description of the workout in the workouts language */
    @SerialName(value = "description") val description: kotlin.String? = null,
    /* Language the video content/info is available in */
    @SerialName(value = "lang") val lang: kotlin.String? = null,
    @SerialName(value = "vimeo_code") val vimeoCode: kotlin.String? = null,
    /* Duration in What format? */
    @SerialName(value = "duration") val duration: kotlin.Double? = null,
    /* What is this? URL? Should probably not be in DB but handled differently */
    @SerialName(value = "thumbnail") val thumbnail: kotlin.String? = null,
    @SerialName(value = "categories") val categories: kotlin.collections.List<VideoCategoryResponse>? = null,
    @SerialName(value = "trainers") val trainers: kotlin.collections.List<TrainerResponse>? = null
) {

    /**
     * 
     * Values: EDUCATION,WORKOUT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "education") EDUCATION("education"),
        @SerialName(value = "workout") WORKOUT("workout");
    }
}

