/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models

import com.myworkout.kotlin.api.models.HitPeriod
import com.myworkout.kotlin.api.models.WorkoutCalculatedEstimatesHealthCondition

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Estimates calculated by the data available
 * @param maxHeartRate 
 * @param healthCondition 
 * @param hitPeriods 
 */
@Serializable
data class WorkoutCalculatedEstimates (
    @SerialName(value = "max_heart_rate") val maxHeartRate: kotlin.Int? = null,
    @SerialName(value = "health_condition") val healthCondition: WorkoutCalculatedEstimatesHealthCondition? = null,
    @SerialName(value = "hit_periods") val hitPeriods: kotlin.collections.List<HitPeriod>? = null
)

