/**
* Myworkout API
* Documentation for Myworkout API 2.  Basic concepts are explained in this section.  # Localization The API supports localization for error messages like validation errors. The preferred way to request language is to set proper `Accept-Language` header, but this can be overriden by adding a `lang` query parameter to the request.  - _Example 1_: `Accept-Language: no` - _Example 2_: `en-GB,en-US;q=0.9,en;q=0.8` 
*
* The version of the OpenAPI document: <%= ENV[\"API_VERSION\"] %>
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.myworkout.kotlin.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param stage 
 * @param startedAt iso8601
 * @param duration seconds
 * @param distance meters
 * @param avgSpeed km/h
 * @param avgPower Power in Watt
 * @param incline Incline in %
 */
@Serializable
data class WorkoutStageInput (
    @SerialName(value = "stage") @Required val stage: WorkoutStageInput.Stage,
    /* iso8601 */
    @SerialName(value = "started_at") @Required val startedAt: kotlin.String,
    /* seconds */
    @SerialName(value = "duration") @Required val duration: kotlin.Int,
    /* meters */
    @SerialName(value = "distance") val distance: kotlin.Double? = null,
    /* km/h */
    @SerialName(value = "avg_speed") val avgSpeed: kotlin.Double? = null,
    /* Power in Watt */
    @SerialName(value = "avg_power") val avgPower: kotlin.Int? = null,
    /* Incline in % */
    @SerialName(value = "incline") val incline: kotlin.Double? = null
) {

    /**
     * 
     * Values: WARM_UP,INTENSIVE,ACTIVE_BREAK,COOL_DOWN,GENERIC
     */
    @Serializable
    enum class Stage(val value: kotlin.String) {
        @SerialName(value = "warm_up") WARM_UP("warm_up"),
        @SerialName(value = "intensive") INTENSIVE("intensive"),
        @SerialName(value = "active_break") ACTIVE_BREAK("active_break"),
        @SerialName(value = "cool_down") COOL_DOWN("cool_down"),
        @SerialName(value = "generic") GENERIC("generic");
    }
}

