name: KaMPKit iOS

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          workspace: ios/KaMPKitiOS.xcworkspace
          scheme: KaMPKitiOS
          destination: platform=iOS Simulator, name=iPhone 8
          sdk: iphoneos
          configuration: Debug
          action: build



